browse/urls.py
from django.conf.urls import patterns, url

from browse import views


urlpatterns = patterns('',
    url(r'^sphere/$', views.sphere, name='sphere'),
    url(r'^register/$', views.register, name='register'),
    url(r'^author/(?P<name>.+)$', views.author, name='author'),
    url(r'^publication/(?P<name>.+)$', views.publication, name='publication'),
    url(r'^read/(?P<hash_id>.+)$', views.read, name='read'),
    url(r'^login/$', views.login_form, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^get_latest_docs/$', views.get_latest_docs, name='get_latest_docs'),
    url(r'^get_latest_revs/$', views.get_latest_revs, name='get_latest_revs'),
    url(r'^get_latest_edits/$', views.get_latest_edits, name='get_latest_edits'),
    url(r'^get_latest_pub_submissions/$', views.get_latest_pub_submissions, name='get_latest_pub_submissions'),
    url(r'^get_latest_bookmarks/$', views.get_latest_bookmarks, name='get_latest_bookmarks'),
    url(r'^add_bookmark/$', views.add_bookmark, name='add_bookmark'),
    url(r'^get_bookmark_offset/$', views.get_bookmark_offset, name='get_bookmark_offset'),
    url(r'^article_previews/(?P<page>.+)$', views.article_previews, name='article_previews'),
    url(r'^page/(?P<page>.+)$', views.browse_page, name='browse_page'),
    url(r'^add_vote$', views.add_vote, name='add_vote'),
    url(r'^save_author_desc$', views.save_author_desc, name='save_author_desc'),
    url(r'^save_pub_desc$', views.save_pub_desc, name='save_pub_desc'),
    url(r'^add_comment_vote$', views.add_comment_vote, name='add_comment_vote'),
    url(r'^add_comment$', views.add_comment, name='add_comment'),
    url(r'^get_comments$', views.get_comments, name='get_comments'),
    url(r'^get_replies$', views.get_replies, name='get_replies'),
    url(r'^get_full_replies$', views.get_full_replies, name='get_full_replies'),
    url(r'^get_subscriptions$', views.get_subscriptions, name='get_subscriptions'),
    url(r'^follow_user$', views.follow_user, name='follow_user'),
    url(r'^follow_pub$', views.follow_pub, name='follow_pub'),
    url(r'^send_message$', views.send_message, name='send_message'),
    url(r'^messages/conversations/(?P<page>.+)$', views.conversations, name='conversations'),
    url(r'^messages/sent/(?P<page>.+)$', views.sent_messages, name='sent_messages'),
    url(r'^messages/(?P<page>.+)$', views.messages, name='messages'),
    url(r'^new_link$', views.new_link, name='new_link'),
    url(r'^follow_tags$', views.follow_tags, name='follow_tags'),
    url(r'^change_subs$', views.change_subs, name='change_subs'),
    url(r'^add_tags$', views.add_tags, name='add_tags'),
    url(r'^toggle_tag$', views.toggle_tag, name='toggle_tag'),
    url(r'^$', views.index, name='index'),
)

edit/urls.py
from django.conf.urls import patterns, url

from edit import views


urlpatterns = patterns('',
    url(r'^myedits/$', views.myedits, name='myedits'),
    url(r'^(?P<hash_id>.+)$', views.edit_draft, name='edit_draft'),
    url(r'^$', views.myedits, name='myedits'),
)

two_cents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'two_cents.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^browse/', include('browse.urls', namespace="browse")),
    url(r'^publish/', include('publish.urls', namespace="publish")),
    url(r'^write/', include('write.urls', namespace="write")),
    url(r'^edit/', include('edit.urls', namespace="edit")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('browse.urls', namespace="browse")),
)

write/urls.py
from django.conf.urls import patterns, url

from write import views


urlpatterns = patterns('',
 #   url(r'^register/$', 'django.contrib.auth.views.login', {'template_name': 'browse/login.html'}),
#    url(r'^login/$', views.login_form, name='login'),
#    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^save_document_as_edit/$', views.save_document_as_edit, name='save_document_as_edit'),
    url(r'^save_document/$', views.save_document, name='save_document'),
    url(r'^request_edit/$', views.request_edit, name='request_edit'),
    url(r'^new/$', views.new, name='new'),
    url(r'^get_doc_version/$', views.get_doc_version, name='get_doc_version'),
    url(r'^new_source/$', views.new_source, name='new_source'),
    url(r'^get_sources/$', views.get_sources, name='get_sources'),
    url(r'^revert/$', views.revert, name='revert'),
    url(r'^new/get_web_content$', views.get_web_content, name='get_web_content'),
    url(r'^(?P<hash_id>.+)$', views.revision, name='revision'),
    url(r'^$', views.mydrafts, name='mydrafts'),
)

edit/models.py
from django.db import models

# Create your models here.

edit/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django import template

register = template.Library()

from django.contrib.auth import authenticate, login, logout, get_user

from browse.models import Document, EditRequest, Publication
from django.contrib.auth.models import User
from browse import views
# Create your views here.

def myedits(request):
    u = get_user(request)
    views.auth_redirect(u, request)
    publication_list = Publication.objects.filter(editors=u)
    context = {'publication_list' : publication_list}
    return render(request, 'edit/myedits.html', context)

def edit_draft(request, hash_id):
    doc = Document.objects.filter(link_hash=hash_id)[0]
#    orig_doc = doc.original_id
#    current_doc = Document.objects.filter(original_id=orig_doc, is_latest=True)[0]
    context = {'selected_doc': doc}
    return render(request, 'edit/editdraft.html', context)

edit/templates/edit/editdraft.html
{% extends "base.html" %}
{% block onReady %}

    $(".saveDocument").on("click", function() {
        //commentPrompt();
});



                $(".addComment").on("click", function() {
                    var d = new Date();
                    var n = d.getTime();
//                    var comment = $('<div class="comment" id=' + n + '>').append($(".commentFormTextarea").val());
//                    var comment = '<div class="comment">' + $(".commentFormTextarea").val() + '</div>';
                    var rightColumnComment = '<a href=#' + n + '>' + $(".commentFormTextarea").val() + '</a>';

                    prependToRightColumn(rightColumnComment);
                    $(".latestMarker").attr("title", $(".commentFormTextarea").val());
                    $(".latestMarker").attr("id", n);
                    
                    $(".latestMarker").tooltip({
                        show: null, // show immediately 
                        content: $(".commentFormTextarea").val(), //from params
                //        track: true,
                        hide: { effect: "" }, //fadeOut
                        close: function(event, ui){
                            ui.tooltip.hover(
                                function () {
                                    $(this).stop(true).fadeTo(400, 1); 
                                },
                                function () {
                                    $(this).fadeOut("400", function(){
                                        $(this).remove(); 
                                    })
                                }
                            );
                        }
                    });
                    $(".ui-helper-hidden-accessible").hide();
                    $(".latestMarker").removeClass("latestMarker");
                    $(".popup").hide();
                    $(".commentFormTextarea").val("");
                });
            
                $(document).on("keydown", function(e) {
                    if (e.keyCode == 188 && e.ctrlKey) {
                        commentPrompt();
                    }
                });

            function commentPrompt() {
                        var image = document.createElement('i');
//                        image.src = "http://placehold.it/15x20";
                        image.className = "commentMarker latestMarker fa fa-comment";
                        try{
                            tracker.insertAtEnd(image, range);
                        } catch(e) {
                        }
                        $(".commentMarker").parent().removeClass("ins");

                        $("#commentFormBorder").css("display", "block");
                        $(".commentFormTextarea").focus();

                        var range = tracker.getCurrentRange();
            }

            function saveDocAsEdit() {
                    alert($("#docId").val());
                    alert($(".title").text());
                    alert($("#textbody").html());
                    var editCount = $(".cts-1").size();
                    var editorsDict = {};
                    $(".cts-1").each(function() {
                        var username = $(this).data("username");
                        editorsDict[username] = 1;
                    });
                    var editorsString = "";
                    for (var key in editorsDict) {
                            editorsString = editorsString.concat(key).concat(":");
                    }
                    alert(editorsString);
                  $.ajax({
                           type: "POST",
                           url: "{% url 'write:save_document_as_edit' %}",
                           data: {'doc_id': $("#docId").val(), 'doc_title': $(".title").text(), 'doc_text': $("#textbody").html(), 'edit_count' : editCount, 'editors_dict' : editorsString, 'csrfmiddlewaretoken': '{{csrf_token}}'},
                           dataType: "text",
                           success: function(response) {
//                                $("#docId").val(response);
                                alert($("#docId").val());
                            },
                            error: function(rs, e) {
                                   alert(rs.responseText);
                            }
                      });

                }

            $(".submitEdit").on("click", function() {
                saveDocAsEdit();

            });



{% endblock %}
{% block headerContent %}

<div class="title" type="text" name="doc_title">{{selected_doc.document_title}}</div>
                <input id="docId" type="hidden" value="{{selected_doc.id}}"/>
{% endblock %}

{% block middleContent %}

        <div class="paddingDiv">
          <div class="extendingColumn"><div class="articlePaddingDiv">
					<div id="textbody" class="editField">
                        <article>{{selected_doc.latest_id.document_text | safe}}</article>
                    </div>	
            </div></div>
  <!--input type="submit" form="publishForm" value="Submit"-->

            <!--div class="submitEdit">Submit Edit</div-->
            
            <script type="text/javascript">
            
            var u_id = "{{user.id}}";
            var u_name = "{{user.username}}";
                
            $(function() {
                window.tracker = new ice.InlineChangeEditor({
                // element to track - ice will make it contenteditable
                element: document.getElementById('textbody'),
                // tell ice to setup/handle events on the `element`
                handleEvents: true,
    
                // set a user object to associate with each change
                currentUser: { id: u_id, name: u_name },
				plugins : ['IceAddTitlePlugin', 'IceSmartQuotesPlugin', 'IceEmdashPlugin', {
						name : 'IceCopyPastePlugin',
						settings : {
							pasteType : 'formattedClean',
							preserve : 'p,a[href],i,em,b,span,ul,ol,li,hr'
						}
					}
				    ]
                });
                // setup and start event handling for track changes
                tracker.startTracking();
            }); 
            </script>
            
              

            
            <div id="commentFormBorder" class="popupFormBorder popup">
                      <div class="popupForm" id="commentForm"><h3>New Comment</h3><textarea form="commentForm" class="commentFormTextarea" name="comment"></textarea>
                          <button class="addComment">Add Comment</button>
                    <button type="button" class="cancel">Cancel</button>
                      </div>
                  </div>
              
</div>
{% endblock %}
{% block leftContent %}

                    <div class="textPaddingDiv"><div class="leftActions"><div class="submitEdit leftAction"><a href="#" class="actionText">Submit Edit</a></div></div></div>
{% endblock %}

edit/templates/edit/index.html
{% extends "base.html" %}
{% block onReady %}

    $(".saveDocument").on("click", function() {
        //commentPrompt();
});



                $(".addComment").on("click", function() {
                    var d = new Date();
                    var n = d.getTime();
//                    var comment = $('<div class="comment" id=' + n + '>').append($(".commentFormTextarea").val());
//                    var comment = '<div class="comment">' + $(".commentFormTextarea").val() + '</div>';
                    var rightColumnComment = '<a href=#' + n + '>' + $(".commentFormTextarea").val() + '</a>';

                    prependToRightColumn(rightColumnComment);
                    $(".latestMarker").attr("title", $(".commentFormTextarea").val());
                    $(".latestMarker").attr("id", n);
                    
                    $(".latestMarker").tooltip({
                        show: null, // show immediately 
                        content: $(".commentFormTextarea").val(), //from params
                //        track: true,
                        hide: { effect: "" }, //fadeOut
                        close: function(event, ui){
                            ui.tooltip.hover(
                                function () {
                                    $(this).stop(true).fadeTo(400, 1); 
                                },
                                function () {
                                    $(this).fadeOut("400", function(){
                                        $(this).remove(); 
                                    })
                                }
                            );
                        }
                    });
                    $(".ui-helper-hidden-accessible").hide();
                    $(".latestMarker").removeClass("latestMarker");
                    $(".popup").hide();
                    $(".commentFormTextarea").val("");
                });
            
                $(document).on("keydown", function(e) {
                    if (e.keyCode == 188 && e.ctrlKey) {
                        commentPrompt();
                    }
                });

            function commentPrompt() {
                        var image = document.createElement('i');
//                        image.src = "http://placehold.it/15x20";
                        image.className = "commentMarker latestMarker fa fa-comment";
                        try{
                            tracker.insertAtEnd(image, range);
                        } catch(e) {
                        }
                        $(".commentMarker").parent().removeClass("ins");

                        $("#commentFormBorder").css("display", "block");
                        $(".commentFormTextarea").focus();

                        var range = tracker.getCurrentRange();
            }

            function saveDocAsEdit() {
                    alert($("#docId").val());
                    alert($(".title").text());
                    alert($("#textbody").html());
                    var editCount = $(".cts-1").size();
                    var editorsDict = {};
                    $(".cts-1").each(function() {
                        var username = $(this).data("username");
                        editorsDict[username] = 1;
                    });
                    var editorsString = "";
                    for (var key in editorsDict) {
                            editorsString = editorsString.concat(key).concat(":");
                    }
                    alert(editorsString);
                  $.ajax({
                           type: "POST",
                           url: "{% url 'write:save_document_as_edit' %}",
                           data: {'doc_id': $("#docId").val(), 'doc_title': $(".title").text(), 'doc_text': $("#textbody").html(), 'edit_count' : editCount, 'editors_dict' : editorsString, 'csrfmiddlewaretoken': '{{csrf_token}}'},
                           dataType: "text",
                           success: function(response) {
//                                $("#docId").val(response);
                                alert($("#docId").val());
                            },
                            error: function(rs, e) {
                                   alert(rs.responseText);
                            }
                      });

                }

            $(".submitEdit").on("click", function() {
                saveDocAsEdit();

            });



{% endblock %}
{% block headerContent %}

<div class="title" type="text" name="doc_title">{{selected_doc.document_title}}</div>
                <input id="docId" type="hidden" value="{{selected_doc.id}}"/>
{% endblock %}

{% block middleContent %}

        <div class="paddingDiv">
          <div class="extendingColumn"><div class="articlePaddingDiv">
					<div id="textbody" class="editField">
                        <article>{{selected_doc.latest_id.document_text | safe}}</article>
                    </div>	
            </div></div>
  <!--input type="submit" form="publishForm" value="Submit"-->

            <!--div class="submitEdit">Submit Edit</div-->
            
            <script type="text/javascript">
            
            var u_id = "{{user.id}}";
            var u_name = "{{user.username}}";
                
            $(function() {
                window.tracker = new ice.InlineChangeEditor({
                // element to track - ice will make it contenteditable
                element: document.getElementById('textbody'),
                // tell ice to setup/handle events on the `element`
                handleEvents: true,
    
                // set a user object to associate with each change
                currentUser: { id: u_id, name: u_name },
				plugins : ['IceAddTitlePlugin', 'IceSmartQuotesPlugin', 'IceEmdashPlugin', {
						name : 'IceCopyPastePlugin',
						settings : {
							pasteType : 'formattedClean',
							preserve : 'p,a[href],i,em,b,span,ul,ol,li,hr'
						}
					}
				    ]
                });
                // setup and start event handling for track changes
                tracker.startTracking();
            }); 
            </script>
            
              

            
            <div id="commentFormBorder" class="popupFormBorder popup">
                      <div class="popupForm" id="commentForm"><h3>New Comment</h3><textarea form="commentForm" class="commentFormTextarea" name="comment"></textarea>
                          <button class="addComment">Add Comment</button>
                    <button type="button" class="cancel">Cancel</button>
                      </div>
                  </div>
              
</div>
{% endblock %}
{% block leftContent %}

                    <div class="textPaddingDiv"><div class="leftActions"><div class="submitEdit leftAction"><a href="#" class="actionText">Submit Edit</a></div></div></div>
{% endblock %}

edit/templates/edit/myedits.html
{% extends "base.html" %}
{% block onReady %}

              $.ajax({
                       type: "POST",
                       url: "{% url 'browse:get_latest_edits' %}",
                       data: {'csrfmiddlewaretoken': '{{csrf_token}}', 'count': 50},
                       dataType: "text",
                       success: function(response) {
                           $(response).find("object").each(function() {
                               title = $(this).find('[name="document_title"]').text();
                               hash = $(this).find('[name="link_hash"]').text();
                               $('.myEditsDiv').append(
                                    $('<div class="middleSelection">').append(
                                        $('<a>').attr('href','/edit/' + hash).append(title)
                                    )
                               );    
                           });
                        },
                        error: function(rs, e) {
                               alert(rs.responseText);
                        }
                  }); 


function addPublicationTab(publication) {
                            var publication_name = publication["publication_name"];
                            var id = publication["id"];
                            $(".topTabs").append(
                                $('<li>').append(
                                    $('<a href="#0">').attr("data-content", publication_name).append(publication_name)
                                )
                            );


                            $(".cd-tabs-content").append(
                                $('<li>').attr("data-content", publication_name).append(
                                    $('<div class="extendingColumn tabbedContent">').append(
                                        $('<div class="articlePaddingDiv">')
                                    )
                                )
                            );
                            addTabListeners();
}



        {% for publication in publication_list %}
            pub = {};
            pub["id"] = "{{publication.id}}";
            pub["publication_name"] = "{{publication.publication_name}}";
            addPublicationTab(pub);
        {% endfor %}

{% endblock %}
{% block middleContent %}

        <div class="paddingDiv">
          <div class="tabsContainer">
                <ul class="topTabs">
                    <li><a data-content="read" class="selected" href="#0">My Edit Requests</a></li>
                </ul> <!-- cd-tabs-navigation -->
              <ul class="cd-tabs-content">
                <li data-content="read" class="selected">
                  <div class="column tabbedContent">
                      <div class="articlePaddingDiv myEditsDiv">
                      </div>
                    </div>
                </li>
              </ul>
        </div>
        </div>

{% endblock %}