browse/urls.py
from django.conf.urls import patterns, url

from browse import views


urlpatterns = patterns('',
    url(r'^sphere/$', views.sphere, name='sphere'),
    url(r'^register/$', views.register, name='register'),
    url(r'^author/(?P<name>.+)$', views.author, name='author'),
    url(r'^publication/(?P<name>.+)$', views.publication, name='publication'),
    url(r'^read/(?P<hash_id>.+)$', views.read, name='read'),
    url(r'^login/$', views.login_form, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^get_latest_docs/$', views.get_latest_docs, name='get_latest_docs'),
    url(r'^get_latest_revs/$', views.get_latest_revs, name='get_latest_revs'),
    url(r'^get_latest_edits/$', views.get_latest_edits, name='get_latest_edits'),
    url(r'^get_latest_pub_submissions/$', views.get_latest_pub_submissions, name='get_latest_pub_submissions'),
    url(r'^get_latest_bookmarks/$', views.get_latest_bookmarks, name='get_latest_bookmarks'),
    url(r'^add_bookmark/$', views.add_bookmark, name='add_bookmark'),
    url(r'^get_bookmark_offset/$', views.get_bookmark_offset, name='get_bookmark_offset'),
    url(r'^article_previews/(?P<page>.+)$', views.article_previews, name='article_previews'),
    url(r'^page/(?P<page>.+)$', views.browse_page, name='browse_page'),
    url(r'^add_vote$', views.add_vote, name='add_vote'),
    url(r'^save_author_desc$', views.save_author_desc, name='save_author_desc'),
    url(r'^save_pub_desc$', views.save_pub_desc, name='save_pub_desc'),
    url(r'^add_comment_vote$', views.add_comment_vote, name='add_comment_vote'),
    url(r'^add_comment$', views.add_comment, name='add_comment'),
    url(r'^get_comments$', views.get_comments, name='get_comments'),
    url(r'^get_replies$', views.get_replies, name='get_replies'),
    url(r'^get_full_replies$', views.get_full_replies, name='get_full_replies'),
    url(r'^get_subscriptions$', views.get_subscriptions, name='get_subscriptions'),
    url(r'^follow_user$', views.follow_user, name='follow_user'),
    url(r'^follow_pub$', views.follow_pub, name='follow_pub'),
    url(r'^send_message$', views.send_message, name='send_message'),
    url(r'^messages/conversations/(?P<page>.+)$', views.conversations, name='conversations'),
    url(r'^messages/sent/(?P<page>.+)$', views.sent_messages, name='sent_messages'),
    url(r'^messages/(?P<page>.+)$', views.messages, name='messages'),
    url(r'^new_link$', views.new_link, name='new_link'),
    url(r'^follow_tags$', views.follow_tags, name='follow_tags'),
    url(r'^change_subs$', views.change_subs, name='change_subs'),
    url(r'^add_tags$', views.add_tags, name='add_tags'),
    url(r'^toggle_tag$', views.toggle_tag, name='toggle_tag'),
    url(r'^$', views.index, name='index'),
)

edit/urls.py
from django.conf.urls import patterns, url

from edit import views


urlpatterns = patterns('',
    url(r'^myedits/$', views.myedits, name='myedits'),
    url(r'^(?P<hash_id>.+)$', views.edit_draft, name='edit_draft'),
    url(r'^$', views.myedits, name='myedits'),
)

publish/urls.py
from django.conf.urls import patterns, url

from publish import views


urlpatterns = patterns('',
    url(r'^mydocs/$', views.mydocs, name='mydocs'),
    url(r'^new_publication/$', views.new_publication, name='new_publication'),
    url(r'^invite_member/$', views.invite_member, name='invite_member'),
    url(r'^get_latest_pubs/$', views.get_latest_pubs, name='get_latest_pubs'),
    url(r'^get_latest_submissions/$', views.get_latest_submissions, name='get_latest_submissions'),
    url(r'^change_permissions/$', views.change_permissions, name='change_permissions'),
    url(r'^change_pub_type/$', views.change_pub_type, name='change_pub_type'),
    url(r'^add_sidebar/$', views.add_sidebar, name='add_sidebar'),
    url(r'^publish_document_to_publication/$', views.publish_document_to_publication, name='publish_document_to_publication'),
    url(r'^publish_document/$', views.publish_document, name='publish_document'),
    url(r'^review/(?P<hash_id>.+)/$', views.review, name='review'),
    url(r'^unlist/$', views.unlist, name='unlist'),
    url(r'^$', views.mydocs, name='mydocs'),
)

two_cents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'two_cents.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^browse/', include('browse.urls', namespace="browse")),
    url(r'^publish/', include('publish.urls', namespace="publish")),
    url(r'^write/', include('write.urls', namespace="write")),
    url(r'^edit/', include('edit.urls', namespace="edit")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('browse.urls', namespace="browse")),
)

browse/models.py
from datetime import datetime
import hashlib
import math

from hashlib import sha1

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Document(models.Model):
#    document_text = models.CharField(max_length=10000, blank=True, default = None)
    document_title = models.CharField(max_length=200)
#    document_version = models.IntegerField(default=0)
#    original_id = models.ForeignKey('self', related_name="orig_id", default=0)
    latest_id = models.ForeignKey('DocumentDraft', related_name="latest_id", default=None, blank=True, null=True)
    user = models.ForeignKey(User)
#    editor = models.ForeignKey(User, related_name="document_editor", default=0)
#    is_edit = models.BooleanField(default = False)
#    is_latest = models.BooleanField(default = False)
    is_published = models.BooleanField(default = False)
#    edit_count = models.IntegerField(default=0)
    editors_list = models.CharField(max_length=200, default="")
    save_date = models.DateTimeField('date saved', default=datetime.now)
    pub_date = models.DateTimeField('date published', null=True)
    link_hash = models.CharField(max_length=50, editable=False, default="")
    has_been_published = models.BooleanField(default = False)
    has_comments = models.BooleanField(default = False)

    def save(self, *args, **kwargs):
        if self.link_hash=="":
            hashstr = self.document_title + str(self.save_date)
            hashstr_utf = hashstr.encode('utf-8')
            self.link_hash = sha1(hashstr_utf).hexdigest()
        super(Document, self).save(*args, **kwargs)
            
    
    def __str__(self):              # __unicode__ on Python 2
        return self.document_title
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    def get_original_id(self):
        if self.original_id is not None:
            return self.original_id
        else:
            return self.id
        
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
class DocumentDraft(models.Model):
    document_text = models.TextField(blank=True, default = None)
    document_version = models.IntegerField(default=0)
    document = models.ForeignKey(Document)
    editor = models.ForeignKey(User, related_name="document_editor", default=None, blank=True, null=True)
    is_edit = models.BooleanField(default = False)
    is_latest = models.BooleanField(default = False)
    edit_count = models.IntegerField(default=0)
    editors_list = models.CharField(max_length=200, default="")
    save_date = models.DateTimeField('date saved', default=datetime.now)

class Tag(models.Model):
    text = models.CharField(max_length=30, blank=False)

class PublishedDocument(models.Model):
    epoch = datetime(1970, 1, 1)
    
    document_text = models.TextField(blank=True)
    preview_text = models.CharField(max_length=1000, blank=True)
    document_title = models.CharField(max_length=200)
    original_id = models.ForeignKey(Document, related_name="orig_doc_id", default=0)
    has_comments = models.BooleanField(default = True)
    unlisted = models.BooleanField(default = False)
    user = models.ForeignKey(User)
    tags = models.ManyToManyField(Tag, related_name="tags")
    pub_date = models.DateTimeField('date published', null=True)
    link_hash = models.CharField(max_length=50, editable=False, default="")
    votes = models.IntegerField(default=1)
    rank = models.FloatField(default=0)

    def save(self, *args, **kwargs):
        self.preview_text = self.document_text[:1000]
        hashstr = self.document_text + self.document_title + str(self.pub_date)
        hashstr_utf = hashstr.encode('utf-8')
        self.link_hash = sha1(hashstr_utf).hexdigest()
        self.calc_rank()
        super(PublishedDocument, self).save(*args, **kwargs)
    
    def calc_rank(self):
        td = self.pub_date.replace(tzinfo=None) - self.epoch.replace(tzinfo=None)
        td_sec = td.days * 86400 + td.seconds + (float(td.microseconds) / 1000000)
        t = td_sec - 1134028003
        order = math.log(max(self.votes, 1), 10)
        self.rank =  round(order + td_sec / 45000, 7)
        
    def inc_votes(self):
        self.votes = self.votes + 1
        self.save()

        
    def dec_votes(self):
        self.votes = self.votes - 1
        if (self.votes < 1):
            self.votes = 1
        self.save()
        
    
    def __str__(self):              # __unicode__ on Python 2
        return self.document_title
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    def get_original_id(self):
        if self.original_id is not None:
            return self.original_id
        else:
            return self.id
        
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
    
class Bookmark(models.Model):
    user = models.ForeignKey(User)
    doc = models.ForeignKey(PublishedDocument)
    offset = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    bookmark_date = models.DateTimeField('date bookmarked')
    
class RecentlyRead(models.Model):
    user = models.ForeignKey(User)
    article = models.ForeignKey(PublishedDocument)
    date = models.DateTimeField(default = datetime.now)

    def save(self, *args, **kwargs):
        self.date = datetime.now()
        super(RecentlyRead, self).save(*args, **kwargs)
    
class Publication(models.Model):
    owner = models.ForeignKey(User)
    editors = models.ManyToManyField(User, related_name="publication_editors")
    writers = models.ManyToManyField(User, related_name="publication_writers")
    articles = models.ManyToManyField(PublishedDocument)
    pendingArticles = models.ManyToManyField(Document)
    accepts_articles = models.BooleanField(default = False)
    is_open = models.BooleanField(default = False)
    description = models.CharField(max_length=1000, blank=True)
    publication_name = models.CharField(max_length=200, default="default")
    last_pub_date = models.DateTimeField('pub_date', null=True)

class PublicationDate(models.Model):
    article = models.ForeignKey(PublishedDocument)
    publication = models.ForeignKey(Publication)
    date = models.DateTimeField(default=datetime.now)

class SubmissionDate(models.Model):
    article = models.ForeignKey(Document)
    publication = models.ForeignKey(Publication)
    date = models.DateTimeField(default=datetime.now)

class Sidebar(models.Model):
    publication = models.ForeignKey(Publication)
    title = models.CharField(max_length=60, blank=True)
    content = models.CharField(max_length=1000, blank=True)

class EditRequest(models.Model):
    writer = models.ForeignKey(User)
    editor = models.ForeignKey(User, related_name="editrequest_editor")
    publication = models.ForeignKey(Publication, null=True)
    comment = models.CharField(max_length=1000, default="")
    doc = models.ForeignKey(Document)
    request_date = models.DateTimeField('date requested')
    
class Citation(models.Model):
    user = models.ForeignKey(User)
    authors = models.CharField(max_length=300, default="")
    publisher = models.CharField(max_length=300, default="")
    title = models.CharField(max_length=300, default="")
    website = models.CharField(max_length=300, default="")
    version = models.CharField(max_length=300, default="")
    url = models.CharField(max_length=300, default="")
    pages = models.CharField(max_length=300, default="")
    source_type = models.CharField(max_length=100, default="")
    pub_date = models.DateTimeField('pub_date', null=True)
    access_date = models.DateTimeField('access_date', null=True)
    document = models.ForeignKey(Document)
    
class Comment(models.Model):
    user = models.ForeignKey(User)
    username = models.CharField(max_length=30, default="Anonymous")
    document = models.ForeignKey(PublishedDocument)
    date = models.DateTimeField('date', default=datetime.now)
    comment_text = models.CharField(max_length=1000, blank=False)
    parent = models.ForeignKey('self', default=None, blank=True, null=True)
    top_comment = models.ForeignKey('self', related_name="topmost_comment", default=None, blank=True, null=True)
    votes = models.IntegerField(default=1)
        
    def inc_votes(self):
        self.votes = self.votes + 1
        self.save()

        
    def dec_votes(self):
        self.votes = self.votes - 1
        if (self.votes < 1):
            self.votes = 1
        self.save()
    
    
class Vote(models.Model):
    user = models.ForeignKey(User)
    document = models.ForeignKey(PublishedDocument, null=True)
    comment = models.ForeignKey(Comment, null=True)
    active = models.BooleanField(default=False)
    
class Notecard(models.Model):
    user = models.ForeignKey(User)
    document = models.ForeignKey(Document)
    source = models.ForeignKey(Citation)
    notecard_text = models.CharField(max_length=10000)
    tag_string = models.CharField(max_length=1000)

class TwoCentsUser(models.Model):
    user = models.OneToOneField(User)
    user_follows = models.ManyToManyField(User, related_name="user_follows")
    pub_follows = models.ManyToManyField(Publication, related_name="pub_follows")
    tag_follows = models.ManyToManyField(Tag, related_name="tag_follows")
    active_tags = models.ManyToManyField(Tag, related_name="active_tags")
    author_description = models.CharField(max_length=1000, blank=True)
    last_pub_date = models.DateTimeField('pub_date', null=True)
    has_unread_message = models.BooleanField(default=False)
    def __str__(self):              # __unicode__ on Python 2
        return self.user.username
    

browse/templates/browse/articles.html
    {% load set_var %}
    {% load increment_var %}
    {% set previewCounter = 0 %}
        {% for document in latest_document_list %}
            {% if forloop.counter|divisibleby:12 %}
                {% set previewCounter = 0 %}
            {% endif %}
              <div class="previewTile{{previewCounter}}">
                <div class="paddingDiv">
                    <div class="articleHeader previewClass{{previewCounter}}">
                        <div class="textPaddingDiv">
<!--                            <form method="post" action="{% url 'browse:add_bookmark' %}" >
                                {% csrf_token %}
                                <input type="image" class="saveForLater" src="http://placehold.it/30x30">
                                <input type="hidden" name="doc_id" value="{{document.id}}">
                                <input type="hidden" name="bookmark_user" value="{{user.id}}">
                            </form-->
                            {% if document.id in bookmarks %}
                            <i class="fa fa-bookmark saveForLater bookmarked" id="bookmark{{document.id}}"></i>
                            {% else %}
                            <i class="fa fa-bookmark saveForLater" id="bookmark{{document.id}}"></i>
                            {% endif %}
                            {% if document.id in doc_votes %}
                            <a class="twoCents activeVote" id="vote{{document.id}}" src="http://placehold.it/30x30" href="#0">2&cent;</a>
                            {% else %}
                            <a class="twoCents" id="vote{{document.id}}" src="http://placehold.it/30x30" href="#0">2&cent;</a>
                            {% endif %}
                            <input class="bookmarkId" type="hidden" name="{{document.id}}">
                            <h2><a href={% url 'browse:read' document.link_hash %} name={{document.link_hash}} class="previewLink">{{ document.document_title }}</a></h2>
                            <h4><a href={% url 'browse:author' document.user.username %}>{{ document.user.username }}</a></h4>
                            <div class="articlePreview">
                                <a href={% url 'browse:read' document.link_hash %}>{{ document.preview_text | safe}}</a>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
                {% increment previewCounter %}
              {% empty %}
                <div class="paddingDiv">
                  <div class="floatingTextDiv"><h3>Uh oh, looks like we couldn't find what you're looking for</h3></div> 
                </div>
              {% endfor %}
<div class="pageNavDiv paddingDiv">
    {% if page|add:"0" > 1 and latest_document_list|length > 0%}
    <div class="prevPage"><a href="{% url 'browse:browse_page' page=page|add:"-1" %}" ><i class="fa fa-angle-left"></i> Previous</a></div>
    {% endif %}
            {% if latest_document_list|length_is:"48" %}
<div class="nextPage"><a href="{% url 'browse:browse_page' page=page|add:"1" %}" >Next <i class="fa fa-angle-right"></i></a></div>
{% endif %}
    
</div>

browse/templates/browse/base.html
 
<form method="post" action="{% url browse:login %}">
  {{ auth_form.non_field_errors }}
  <p>
    {{ auth_form.username.errors }}
    <label for="id_username">{% trans "Username" %}:</label> <input type="text" name="username" id="id_username"> 
  </p>
  <p>
    {{ auth_form.password.errors }}
    <label for="id_password">{% trans "Password" %}:</label> <input type="text" name="password" id="id_password"> 
  </p>
  <p>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    <input type="submit" value="{% trans "Log in" %}">
    <input type="hidden" name="next" value="{{ next }}">
  </p>
</form>

browse/templates/browse/login.html
<form action="{% url 'browse:login' %}" method="post">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

browse/templates/browse/publication.html
{% extends "base.html" %}
{% block onReady %}

//var pubs = {{publications | safe}};

//for (var key in pubs) {
//    var pub_name = pubs[key]["fields"]["publication_name"];
//    $(".authorPubs").find("ul").append($('<li>').append($('<a>').attr("href", "/browse/publication/" + pub_name).append(pub_name)));
//}

{% if publication.owner == user %}
    $(".profileEditLink").on("click", function() {
        $(".aboutThePub").attr("contenteditable", true);
        $(".aboutThePub").focus();
    });
    $(".aboutThePub").on("keyup", function() {
        $(".aboutThePub").attr("display", "block");
        $(".saveEditLink").show();
    });

    $(".newSidebar").on("click", function() {
        $("#newSidebarBorder").show();
    });

   $(".saveEditLink").on("click", function() {
      $.ajax({
               type: "POST",
               url: "{% url 'browse:save_pub_desc' %}",
               data: {'desc': $(".aboutThePub").html(), 'publication_id': {{publication.id}}, 'csrfmiddlewaretoken': '{{csrf_token}}'},
               dataType: "html",
               success: function(response) {
                    $(".aboutThePub").html(response);
                    $(".aboutThePub").attr("contenteditable", false);
                    $(".saveEditLink").hide();
                },
                error: function(rs, e) {
                       alert(rs.responseText);
                }
          });

    });

   $(".addSidebar").on("click", function() {
      $.ajax({
               type: "POST",
               url: "{% url 'publish:add_sidebar' %}",
               data: {'content': $(".newSidebarContent").html(), 'title' : $(".newSidebarTitle").val(), 'publication_id': {{publication.id}}, 'csrfmiddlewaretoken': '{{csrf_token}}'},
               dataType: "html",
               success: function(response) {
                    var $sidebar = $('<div class="paddingDiv">').append(
                                        $('<div class="column">').append(
                                            $('<div class="textPaddingDiv">').append(
                                                $('<b>').append($(".newSidebarTitle").val())
                                            ).append($('<a href="#0" class="profileEditLink">Edit</a><br>')).append(
                                                $('<div class="aboutThePub">').html(response)
                                            ).append($('<a href="#0" class="saveEditLink">Save Changes</a>'))
                                        )
                                    );

                    $(".newSidebars").append($sidebar);

                    $(".popupFormBorder").hide();
                    
//                    $(".aboutThePub").html(response);
//                    $(".aboutThePub").attr("contenteditable", false);
//                    $(".saveEditLink").hide();
                },
                error: function(rs, e) {
                       alert(rs.responseText);
                }
          });

    });
{% else %}

   $(".subscribeButton").on("click", function() {
      $.ajax({
               type: "POST",
               url: "{% url 'browse:follow_pub' %}",
               data: {'publication_id': "{{publication.id}}", 'csrfmiddlewaretoken': '{{csrf_token}}'},
               dataType: "text",
               success: function(response) {
                    $(".subscribeButton i").toggleClass("fa-check");
                    $(".subscribeButton i").toggleClass("fa-user-plus");
                    if ($(".subscribeButton i").hasClass("fa-check")) {
                        $(".subscribeButton").text("Subscribed ").append($('<i class="fa fa-check"></i>'));
                    } else {
                        $(".subscribeButton").text("Subscribe ").append($('<i class="fa fa-user-plus"></i>'));
                    }
                },
                error: function(rs, e) {
                       alert(rs.responseText);
                }
          });

    });

{% endif %}
$(".sendMessage").on("click", function() {
    $("#messageFormBorder").show();
});
$(".addLink").on("click", function() {
    $("#newLinkFormBorder").show();
});
{% endblock %}
{% block headerContent %}
{% if subscribed %}
<a href="#0"><div class="subscribeButton">Subscribed <i class="fa fa-check"></i></div></a>
{% else %}
<a href="#0"><div class="subscribeButton">Subscribe <i class="fa fa-user-plus"></i></div></a>
{% endif %}
<div class="title" name="author_name">{{publication.publication_name}}</div>
{% endblock %}

{% block middleContent %}

    {% load set_var %}
    {% load increment_var %}
    {% set previewCounter = 0 %}
        {% for document in latest_document_list %}
            {% if forloop.counter|divisibleby:12 %}
                {% set previewCounter = 0 %}
            {% endif %}
              <div class="previewTile{{previewCounter}}">
                <div class="paddingDiv">
                    <div class="articleHeader previewClass{{previewCounter}}">
                        <div class="textPaddingDiv">
<!--                            <form method="post" action="{% url 'browse:add_bookmark' %}" >
                                {% csrf_token %}
                                <input type="image" class="saveForLater" src="http://placehold.it/30x30">
                                <input type="hidden" name="doc_id" value="{{document.id}}">
                                <input type="hidden" name="bookmark_user" value="{{user.id}}">
                            </form-->
                            {% if document.id in bookmarks %}
                            <i class="fa fa-bookmark saveForLater bookmarked" id="bookmark{{document.id}}"></i>
                            {% else %}
                            <i class="fa fa-bookmark saveForLater" id="bookmark{{document.id}}"></i>
                            {% endif %}
                            {% if document.id in doc_votes %}
                            <a class="twoCents activeVote" id="vote{{document.id}}" src="http://placehold.it/30x30" href="#0">2&cent;</a>
                            {% else %}
                            <a class="twoCents" id="vote{{document.id}}" src="http://placehold.it/30x30" href="#0">2&cent;</a>
                            {% endif %}
                            <input class="bookmarkId" type="hidden" name="{{document.id}}">
                            <h2><a href={% url 'browse:read' document.link_hash %} name={{document.link_hash}}>{{ document.document_title }}</a></h2>
                            <h4><a href={% url 'browse:author' document.user.username %}>{{ document.user.username }}</a></h4>
                            <div class="articlePreview">
                                <a href={% url 'browse:read' document.link_hash %} class="previewLink">{{ document.document_text | safe}}</a>
                            </div>
                        </div>
                    </div>
                </div>
                  
            
            <div id="messageFormBorder" class="popupFormBorder popup">
                      <form class="popupForm messageForm" id="messageForm" action="{% url 'browse:send_message' %}" method="post">{% csrf_token %}<h3>New Message</h3><h4>To: {{author.username}}</h4><textarea name="message_content"></textarea>
                            <input type="hidden" name="recipient" value="{{author.username}}">
                          <input type="submit" value="Send">
                    <button type="button" class="cancel"><i class="fa fa-times"></i></button>
                      </form>
                  </div>
              <!--/div>
              <div  class="previewTile{{previewCounter}}">
                <div class="paddingDiv">
                    <div class="articleHeader{{previewCounter}}"><div class="textPaddingDiv"><img class="saveForLater" src="http://placehold.it/30x30"><h2>{{ document.document_title }}</h2><h4>{{ document.user.username }}</h4><div class="articlePreview">{{ document.document_text }}</div></div></div>
                </div>
              </div>
              <div  class="previewTile{{previewCounter}}">
                <div class="paddingDiv">
                    <div class="articleHeader{{previewCounter}}" style="height:612px"><div class="textPaddingDiv"><img class="saveForLater" src="http://placehold.it/30x30"><h2>{{ document.document_title }}</h2><h4>{{ document.user.username }}</h4><div class="articlePreview">{{ document.document_text }}</div></div></div>
                </div>
              </div>
              <div  class="previewTile{{previewCounter}}">
                <div class="paddingDiv">
                    <div class="articleHeader{{previewCounter}}"><div class="textPaddingDiv"><img class="saveForLater" src="http://placehold.it/30x30"><h2>{{ document.document_title }}</h2><h4>{{ document.user.username }}</h4><div class="articlePreview"></div>{{ document.document_text }}</div></div>
                </div-->
              </div>
                {% increment previewCounter %}
              {% empty %}
                <div class="paddingDiv">
                  <div class="floatingTextDiv"><h3>This publication doesn't have any articles yet</h3></div> 
                </div>
              {% endfor %}

            
            <div id="newLinkFormBorder" class="popupFormBorder popup">
                      <form class="popupForm" id="newLinkForm" action="{% url 'browse:new_link' %}" method="post">{% csrf_token %}<h3>New Link</h3>
                          <h4 class="sourceInputName">Destination</h4><input type="text" name="href"/><br>
                          <h4 class="sourceInputName">Display Name</h4><input type="text" name="display_name"/><br>
                    <input type="submit" value="Create Link">
                    <button type="button" class="cancel"><i class="fa fa-times"></i></button>
                      </form>
                  </div>
            
            <div id="newSidebarBorder" class="popupFormBorder popup">
                      <form class="popupForm" id="newSidebarForm" action="{% url 'browse:new_link' %}" method="post">{% csrf_token %}<h3>New Sidebar</h3>
                          <h4 class="sourceInputName">Title</h4><input type="text" name="href" class="newSidebarTitle"/><br>
                          <h4 class="sourceInputName">Content</h4><div class="newSidebarContent" contenteditable="true"></div><br>
                          <button type="button" class="addSidebar">Add Sidebar</button>
                    <button type="button" class="cancel"><i class="fa fa-times"></i></button>
                      </form>
                  </div>
{% endblock %}
{% block rightContent %}
{% if user == publication.owner %}
<div class="paddingDiv">
    <a href="#0" class="newSidebar clickable"><i class="fa fa-plus"></i> New Sidebar</a>
</div>
{% endif %}
<div class="paddingDiv">
    <div class="column">
        <div class="textPaddingDiv">
            <b>About the Publication</b>{% if user == publication.owner %}<a href="#0" class="profileEditLink">Edit</a>{% endif %}<br>
            <div class="aboutThePub">{{publication.description | safe}}</div>{% if user == publication.owner %}<a href="#0" class="saveEditLink">Save Changes</a>{% endif %}
        </div>
    </div>
</div>
<div class="paddingDiv">
    <div class="column">
        <div class="textPaddingDiv">
            <b>Editors</b><br>
        {% for editor in publication.editors.all %}
            <a href="/browse/author/{{editor.username}}">{{editor.username}}</a><br>
        {% endfor %}
        </div>
    </div>
</div>
{% for sidebar in publication.sidebar_set.all %}
<div class="paddingDiv">
    <div class="column">
        <div class="textPaddingDiv">
            <b>{{sidebar.title}}</b>{% if user == publication.owner %}<a href="#0" class="profileEditLink">Edit</a>{% endif %}<br>
            <div class="aboutThePub">{{sidebar.content | safe}}</div>{% if user == publication.owner %}<a href="#0" class="saveEditLink">Save Changes</a>{% endif %}
        </div>
    </div>
</div>
{% endfor %}
<div class="newSidebars"></div>
{% endblock %}
{% block leftContent %}


                    <div class="textPaddingDiv">
                        <div class="leftActions">
                            <div class="manageSubscriptions"><a href="#" class="actionText">Manage Subscriptions</a></div>
                        </div>
                    </div>

{% endblock %}