edit/urls.py
from django.conf.urls import patterns, url

from edit import views


urlpatterns = patterns('',
    url(r'^myedits/$', views.myedits, name='myedits'),
    url(r'^(?P<hash_id>.+)$', views.edit_draft, name='edit_draft'),
    url(r'^$', views.myedits, name='myedits'),
)

publish/urls.py
from django.conf.urls import patterns, url

from publish import views


urlpatterns = patterns('',
    url(r'^mydocs/$', views.mydocs, name='mydocs'),
    url(r'^new_publication/$', views.new_publication, name='new_publication'),
    url(r'^invite_member/$', views.invite_member, name='invite_member'),
    url(r'^get_latest_pubs/$', views.get_latest_pubs, name='get_latest_pubs'),
    url(r'^get_latest_submissions/$', views.get_latest_submissions, name='get_latest_submissions'),
    url(r'^change_permissions/$', views.change_permissions, name='change_permissions'),
    url(r'^change_pub_type/$', views.change_pub_type, name='change_pub_type'),
    url(r'^add_sidebar/$', views.add_sidebar, name='add_sidebar'),
    url(r'^publish_document_to_publication/$', views.publish_document_to_publication, name='publish_document_to_publication'),
    url(r'^publish_document/$', views.publish_document, name='publish_document'),
    url(r'^review/(?P<hash_id>.+)/$', views.review, name='review'),
    url(r'^unlist/$', views.unlist, name='unlist'),
    url(r'^$', views.mydocs, name='mydocs'),
)

two_cents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'two_cents.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^browse/', include('browse.urls', namespace="browse")),
    url(r'^publish/', include('publish.urls', namespace="publish")),
    url(r'^write/', include('write.urls', namespace="write")),
    url(r'^edit/', include('edit.urls', namespace="edit")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('browse.urls', namespace="browse")),
)

write/urls.py
from django.conf.urls import patterns, url

from write import views


urlpatterns = patterns('',
 #   url(r'^register/$', 'django.contrib.auth.views.login', {'template_name': 'browse/login.html'}),
#    url(r'^login/$', views.login_form, name='login'),
#    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^save_document_as_edit/$', views.save_document_as_edit, name='save_document_as_edit'),
    url(r'^save_document/$', views.save_document, name='save_document'),
    url(r'^request_edit/$', views.request_edit, name='request_edit'),
    url(r'^new/$', views.new, name='new'),
    url(r'^get_doc_version/$', views.get_doc_version, name='get_doc_version'),
    url(r'^new_source/$', views.new_source, name='new_source'),
    url(r'^get_sources/$', views.get_sources, name='get_sources'),
    url(r'^revert/$', views.revert, name='revert'),
    url(r'^new/get_web_content$', views.get_web_content, name='get_web_content'),
    url(r'^(?P<hash_id>.+)$', views.revision, name='revision'),
    url(r'^$', views.mydrafts, name='mydrafts'),
)

publish/models.py
from django.db import models

# Create your models here.

publish/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django import template
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import json

register = template.Library()

from django.contrib.auth import authenticate, login, logout, get_user

from browse.models import Document, PublishedDocument, EditRequest, Publication, Sidebar, SubmissionDate, PublicationDate
from browse import views
from django.contrib.auth.models import User
# Create your views here.




def review(request, hash_id):
    u = get_user(request)
    views.auth_redirect(u, request)
    doc = Document.objects.filter(link_hash=hash_id)[0]
#    orig_doc = doc.original_id
#    current_doc = Document.objects.filter(original_id=orig_doc, is_latest=True)[0]
    context = {'selected_doc': doc}
    return render(request, 'publish/review.html', context)

def mydocs(request):
    u = get_user(request)
    views.auth_redirect(u, request)
    publication_list = Publication.objects.filter(editors=u)
    write_member_list = Publication.objects.filter(writers=u)
    context = {'publication_list': publication_list, 'write_member_list': write_member_list}
    return render(request, 'publish/mydocs.html', context)

def publish_document(request):
    submission_type = request.POST['submissionType']
    hash_id = request.POST['docHash']
    if submission_type == "Publish" or submission_type == "Unlist":
        return(publish_document_to_publication(request))
    
    orig_doc = Document.objects.filter(link_hash=hash_id)[0]
    if submission_type == "Submit to Publication":
        pub_name = request.POST['submit_publication_name']
        pub = Publication.objects.get(publication_name=pub_name)
        if (pub.is_open):
            orig_doc.has_been_published = True;
            orig_doc.save()
            current_doc = orig_doc.latest_id
#            current_doc = Document.objects.filter(original_id=orig_doc, is_latest=True, is_edit=False)[0]
#            Document.objects.filter(original_id=orig_doc).update(has_been_published=True)
            doc_text = current_doc.document_text
            doc_title = orig_doc.document_title
            u = orig_doc.user
            try:
                d = PublishedDocument.objects.get(original_id = orig_doc)
                d.unlisted = False
            except:
                d = PublishedDocument(original_id=orig_doc, user=u, document_text=doc_text, document_title=doc_title, pub_date=timezone.now())
            d.save()
            pub.articles.add(d)
            pub.last_pub_date = d.pub_date
            pub.save()
            tcu = u.twocentsuser
            tcu.last_pub_date = d.pub_date
            tcu.save()
#        orig_doc = doc.original_id
        else:
            if (pub.pendingArticles.filter(pk = orig_doc.id).exists() != True):
                sub_date = SubmissionDate(publication = pub, article = orig_doc)
                sub_date.save()
                pub.pendingArticles.add(orig_doc)
        pub.save()
    else:
 #       orig_doc = doc.original_id
        try:
            current_pub = PublishedDocument.objects.get(original_id = orig_doc)
            current_pub.unlisted = False
            current_pub.save()
        except:
            orig_doc.has_been_published = True;
            orig_doc.save()
            current_doc = orig_doc.latest_id
#            current_doc = Document.objects.filter(original_id=orig_doc, is_latest=True, is_edit=False)[0]
#            Document.objects.filter(original_id=orig_doc).update(has_been_published=True)
            doc_text = current_doc.document_text
            doc_title = orig_doc.document_title
            u = orig_doc.user
            d = PublishedDocument(original_id=orig_doc, user=u, document_text=doc_text, document_title=doc_title, pub_date=timezone.now())
            d.save()
            tcu = u.twocentsuser
            tcu.last_pub_date = d.pub_date
            tcu.save()

    return HttpResponseRedirect(reverse('browse:index'))

def publish_document_to_publication(request):
    hash_id = request.POST['docHash']
    pub_name = request.POST['publication_name']
    submission_type = request.POST['submissionType']
    pub = Publication.objects.get(publication_name=pub_name)
    pub_user = get_user(request)
#    orig_doc = doc.original_id
    comment = request.POST.get('comment', "")

    if (submission_type == "Publish"):
        try:
            orig_doc = Document.objects.get(link_hash=hash_id)
            d = PublishedDocument.objects.get(original_id = orig_doc)
            d.unlisted = False
            d.save()
        except:
            orig_doc.has_been_published = True;
            orig_doc.save()
            current_doc = orig_doc.latest_id
    #        current_doc = Document.objects.filter(original_id=orig_doc, is_latest=True, is_edit=False)[0]
    #        Document.objects.filter(original_id=orig_doc).update(has_been_published=True)
            doc_text = current_doc.document_text
            doc_title = orig_doc.document_title
            u = orig_doc.user
            d = PublishedDocument(original_id=orig_doc, user=u, document_text=doc_text, document_title=doc_title, pub_date=timezone.now())
            d.save()
        pub.pendingArticles.remove(orig_doc)
        pub_date =PublicationDate(publication = pub, article = d)
        pub_date.save()
        pub.articles.add(d)
        pub.last_pub_date = d.pub_date
        text = pub_user.username + " published the document <b><a href='/browse/read/" + d.link_hash + "'>" + d.document_title + "</a></b> to the publication <b><a href='/browse/publication/" + pub_name + "'>" + pub_name + "</a></b><br>" + comment

    elif (submission_type == "Unlist"):
        d = PublishedDocument.objects.get(link_hash = hash_id)
        pub.articles.remove(d)
        text = pub_user.username + " unlisted the document <b><a href='/browse/read/" + d.link_hash + "'>" + d.document_title + "</a></b> from the publication <b><a href='/browse/publication/" + pub_name + "'>" + pub_name + "</a></b><br>" + comment
        
    elif (submission_type == "Reject"):
        d = Document.objects.get(link_hash = hash_id)
        pub.pendingArticles.remove(d)
        text = pub_user.username + " unlisted the document <b><a href='/browse/read/" + d.link_hash + "'>" + d.document_title + "</a></b> from the publication <b><a href='/browse/publication/" + pub_name + "'>" + pub_name + "</a></b><br>" + comment

    pub.save()
    
    if (pub_user != d.user):
        views.send_message_with_args(request, d.user.username, text, pub_user)
    
    return HttpResponse(d.link_hash)

def new_publication(request):
    pub_name = request.POST['new_publication_name']
    u = get_user(request)
    try:
        pub = Publication.objects.get(publication_name=pub_name)
        return HttpResponse("Publication already exists")
    except:
        pub = Publication(owner= u, publication_name = pub_name)
        pub.save()
        pub.editors.add(u)
        pub.writers.add(u)
        pub.save()
        return HttpResponseRedirect(reverse('publish:mydocs'))
        
def invite_member(request):
    pub_name = request.POST['publication_name']
    member_name = request.POST['username']
    pub = Publication.objects.get(publication_name=pub_name)
    u = User.objects.get(username=member_name)
    pub.writers.add(u)
    pub.save()
    return HttpResponse(member_name)
        
def change_permissions(request):
    pub_name = request.POST['publication_name']
    member_name = request.POST['memberPermissionSelect']
    submission_type = request.POST['submissionType']
    pub = Publication.objects.get(publication_name=pub_name)
    u = User.objects.get(username=member_name)
    if submission_type == "Remove Member":
        pub.editors.remove(u)
        pub.writers.remove(u)
    else:
        if 'canEdit' in request.POST:
            pub.editors.add(u)
        else:
            pub.editors.remove(u)
    pub.save()
    return HttpResponse(pub.publication_name)

def change_pub_type(request):
    pub_type = request.POST['pub_type']
    pub_name = request.POST['publication_name']
    pub = Publication.objects.get(publication_name=pub_name)
    if(pub_type == "open_publication"):
        pub.is_open = True;
    elif(pub_type == "open_submission"):
        pub.is_open = False;
        pub.accepts_articles = True;
    else:
        pub.is_open = False;
        pub.accepts_articles = False;
    pub.save()
    return HttpResponse(pub.publication_name)

def get_latest_submissions(request):
    pub_name = request.GET['publication_name']
    page = request.GET['page']
    pub = Publication.objects.get(publication_name=pub_name)
    pending_articles = pub.pendingArticles.all()

    paginator = Paginator(pending_articles, 30)
    try:
        returned_articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        returned_articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        returned_articles = paginator.page(paginator.num_pages)
        
    article_hashes = {}
    for article in returned_articles:
        sub_date = SubmissionDate.objects.get(publication = pub, article = article)
        article_hashes[article.document_title] = [article.link_hash, sub_date.date.strftime('%H:%M %Y-%m-%d '), article.user.username]
    context = {"pending_articles":article_hashes}
    return HttpResponse(json.dumps(context))

def get_latest_pubs(request):
    pub_name = request.GET['publication_name']
    page = request.GET['page']
    pub = Publication.objects.get(publication_name=pub_name)
    articles = pub.articles.all()

    paginator = Paginator(articles, 30)
    try:
        returned_articles = paginator.page(page)
    except PageNotAnInteger:

publish/templates/publish/review.html
{% extends "base.html" %}
{% block onReady %}

function addCitations(citationList) {

    $(citationList).find("object").each(function() {
        author = $(this).find('[name="authors"]').text().split(",");
        authorArray = author[0].split(" ");
        formattedAuthor = authorArray[authorArray.length - 1] + ", " + authorArray.slice(0, -1).join(" ");
        if (author.length > 1) {
            formattedAuthors = formattedAuthor + author.slice(1, -1).join(", ") + ", and " + author[author.length - 1];
        } else {
            formattedAuthors = formattedAuthor;
        }
        if (formattedAuthors[formattedAuthors.length -1] != ".") {
            formattedAuthors = formattedAuthors + ". "
        } else {
            formattedAuthors = formattedAuthors + " "
        }
        var citation = $('<div class="citation">');
        citation.append(formattedAuthors);
        citation.append($('<i>').append($(this).find('[name="title"]').text() + ". "));
        citation.append($(this).find('[name="publisher"]').text() + ", ");
        date = new Date($(this).find('[name="pub_date"]').text());
        citation.append(date.getFullYear() + ". Print.");
        $("#bibContent").append(citation);
    });

}

                  $.ajax({
                           type: "GET",
                           url: "{% url 'write:get_sources' %}",
                           data: {'doc_id': {{selected_doc.id}}, 'csrfmiddlewaretoken': '{{csrf_token}}'},
                           dataType: "text",
                           success: function(response) {
                                addCitations(response);
                            },
                            error: function(rs, e) {
                                   alert(rs.responseText);
                            }
                      });  


{% endblock %}
{% block headerContent %}

<form action="{% url 'publish:publish_document' %}" method="post" id="publishForm">
    {% csrf_token %}
                <input class="title" type="text" name="doc_title" value="{{selected_doc.document_title}}"/>
                <input id="docId" type="hidden" value="{{selected_doc.id}}"/>
</form>

{% endblock %}

{% block middleContent %}
        <div class="paddingDiv">
            
            
  <div class="tabsContainer">
      <nav>
		<ul class="topTabs">
			<li><a data-content="read" class="selected" href="#0">Read</a></li>
			<li><a data-content="bibliography" href="#0">Bibliography</a></li>
		</ul> <!-- cd-tabs-navigation -->
      </nav>
      <ul class="cd-tabs-content">
		<li data-content="write" class="selected">
            <div class="extendingColumn tabbedContent"><div class="articlePaddingDiv"><div id="textbody" class="textbody"x>{{selected_doc.latest_id.document_text | safe}}</div></div></div>
            
        </li>
		<li data-content="bibliography">
                <div class="extendingColumn tabbedContent">
            
                    <div class="articlePaddingDiv" id="bibContent" ></a></div>
                </div>
            
        </li>
      </ul>
</div>
</div>

<div id="autoSave">Auto Saved</div>

{% endblock %}
{% block leftContent %}

                    <div class="textPaddingDiv">
                        <div class="leftActions">
                            <div class="publishToPub leftAction"><a href="#" class="actionText">Publish</a></div>
                        </div>
                    </div>
{% endblock %}