browse/urls.py
from django.conf.urls import patterns, url

from browse import views


urlpatterns = patterns('',
    url(r'^sphere/$', views.sphere, name='sphere'),
    url(r'^register/$', views.register, name='register'),
    url(r'^author/(?P<name>.+)$', views.author, name='author'),
    url(r'^publication/(?P<name>.+)$', views.publication, name='publication'),
    url(r'^read/(?P<hash_id>.+)$', views.read, name='read'),
    url(r'^login/$', views.login_form, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^get_latest_docs/$', views.get_latest_docs, name='get_latest_docs'),
    url(r'^get_latest_revs/$', views.get_latest_revs, name='get_latest_revs'),
    url(r'^get_latest_edits/$', views.get_latest_edits, name='get_latest_edits'),
    url(r'^get_latest_pub_submissions/$', views.get_latest_pub_submissions, name='get_latest_pub_submissions'),
    url(r'^get_latest_bookmarks/$', views.get_latest_bookmarks, name='get_latest_bookmarks'),
    url(r'^add_bookmark/$', views.add_bookmark, name='add_bookmark'),
    url(r'^get_bookmark_offset/$', views.get_bookmark_offset, name='get_bookmark_offset'),
    url(r'^article_previews/(?P<page>.+)$', views.article_previews, name='article_previews'),
    url(r'^page/(?P<page>.+)$', views.browse_page, name='browse_page'),
    url(r'^add_vote$', views.add_vote, name='add_vote'),
    url(r'^save_author_desc$', views.save_author_desc, name='save_author_desc'),
    url(r'^save_pub_desc$', views.save_pub_desc, name='save_pub_desc'),
    url(r'^add_comment_vote$', views.add_comment_vote, name='add_comment_vote'),
    url(r'^add_comment$', views.add_comment, name='add_comment'),
    url(r'^get_comments$', views.get_comments, name='get_comments'),
    url(r'^get_replies$', views.get_replies, name='get_replies'),
    url(r'^get_full_replies$', views.get_full_replies, name='get_full_replies'),
    url(r'^get_subscriptions$', views.get_subscriptions, name='get_subscriptions'),
    url(r'^follow_user$', views.follow_user, name='follow_user'),
    url(r'^follow_pub$', views.follow_pub, name='follow_pub'),
    url(r'^send_message$', views.send_message, name='send_message'),
    url(r'^messages/conversations/(?P<page>.+)$', views.conversations, name='conversations'),
    url(r'^messages/sent/(?P<page>.+)$', views.sent_messages, name='sent_messages'),
    url(r'^messages/(?P<page>.+)$', views.messages, name='messages'),
    url(r'^new_link$', views.new_link, name='new_link'),
    url(r'^follow_tags$', views.follow_tags, name='follow_tags'),
    url(r'^change_subs$', views.change_subs, name='change_subs'),
    url(r'^add_tags$', views.add_tags, name='add_tags'),
    url(r'^toggle_tag$', views.toggle_tag, name='toggle_tag'),
    url(r'^$', views.index, name='index'),
)

edit/urls.py
from django.conf.urls import patterns, url

from edit import views


urlpatterns = patterns('',
    url(r'^myedits/$', views.myedits, name='myedits'),
    url(r'^(?P<hash_id>.+)$', views.edit_draft, name='edit_draft'),
    url(r'^$', views.myedits, name='myedits'),
)

publish/urls.py
from django.conf.urls import patterns, url

from publish import views


urlpatterns = patterns('',
    url(r'^mydocs/$', views.mydocs, name='mydocs'),
    url(r'^new_publication/$', views.new_publication, name='new_publication'),
    url(r'^invite_member/$', views.invite_member, name='invite_member'),
    url(r'^get_latest_pubs/$', views.get_latest_pubs, name='get_latest_pubs'),
    url(r'^get_latest_submissions/$', views.get_latest_submissions, name='get_latest_submissions'),
    url(r'^change_permissions/$', views.change_permissions, name='change_permissions'),
    url(r'^change_pub_type/$', views.change_pub_type, name='change_pub_type'),
    url(r'^add_sidebar/$', views.add_sidebar, name='add_sidebar'),
    url(r'^publish_document_to_publication/$', views.publish_document_to_publication, name='publish_document_to_publication'),
    url(r'^publish_document/$', views.publish_document, name='publish_document'),
    url(r'^review/(?P<hash_id>.+)/$', views.review, name='review'),
    url(r'^unlist/$', views.unlist, name='unlist'),
    url(r'^$', views.mydocs, name='mydocs'),
)

two_cents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'two_cents.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^browse/', include('browse.urls', namespace="browse")),
    url(r'^publish/', include('publish.urls', namespace="publish")),
    url(r'^write/', include('write.urls', namespace="write")),
    url(r'^edit/', include('edit.urls', namespace="edit")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('browse.urls', namespace="browse")),
)

write/urls.py
from django.conf.urls import patterns, url

from write import views


urlpatterns = patterns('',
 #   url(r'^register/$', 'django.contrib.auth.views.login', {'template_name': 'browse/login.html'}),
#    url(r'^login/$', views.login_form, name='login'),
#    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^save_document_as_edit/$', views.save_document_as_edit, name='save_document_as_edit'),
    url(r'^save_document/$', views.save_document, name='save_document'),
    url(r'^request_edit/$', views.request_edit, name='request_edit'),
    url(r'^new/$', views.new, name='new'),
    url(r'^get_doc_version/$', views.get_doc_version, name='get_doc_version'),
    url(r'^new_source/$', views.new_source, name='new_source'),
    url(r'^get_sources/$', views.get_sources, name='get_sources'),
    url(r'^revert/$', views.revert, name='revert'),
    url(r'^new/get_web_content$', views.get_web_content, name='get_web_content'),
    url(r'^(?P<hash_id>.+)$', views.revision, name='revision'),
    url(r'^$', views.mydrafts, name='mydrafts'),
)

write/models.py
from django.db import models

# Create your models here.

write/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django import template

import requests
import lxml
from lxml import html

import urlparse

from django.core import serializers

import json
from datetime import datetime

import isbnlib

register = template.Library()

from django.contrib.auth import authenticate, login, logout, get_user

from browse.models import Document, EditRequest, Citation, Message, TwoCentsUser, DocumentDraft
from django.contrib.auth.models import User
from browse import views
# Create your views here.


def mydrafts(request):
    u = get_user(request)
    latest_document_list = Document.objects.filter(save_date__lte=timezone.now(), has_been_published=False).order_by('-save_date')[:16]
    context = {'latest_document_list': latest_document_list}
    return render(request, 'write/mydrafts.html', context)



def revision(request, hash_id):
    doc = Document.objects.filter(link_hash=hash_id)[0]
#    orig_doc = doc.original_id
#    current_doc = Document.objects.filter(original_id=orig_doc, is_latest=True)[0]
    context = {'selected_doc': doc}
    return render(request, 'write/new.html', context)

def new(request):
    u = get_user(request)
    views.auth_redirect(u, request)
    doc_title = request.POST['doc_title']
    starter_html = request.POST['starter_html']
    if len(starter_html) > 0:
        new_doc_id = save_doc_in_db(request, starter_html, doc_title, "", "")
    else:
        new_doc_id = save_doc_in_db(request, "", doc_title, "", "")
    doc = Document.objects.get(pk=new_doc_id)
    domain = 'http://ec2-54-174-71-237.compute-1.amazonaws.com'
    destination = reverse('write:revision', kwargs= {'hash_id' : doc.link_hash})   
    full_address = urlparse.urljoin(domain, destination)
    return HttpResponseRedirect(full_address)
#    return revision(request, doc.link_hash)

def save_doc_in_db(request, doc_text, doc_title, doc_id, editorsString):    

    u = get_user(request)
    prev_doc = None
    try:
        orig_doc = Document.objects.get(pk=doc_id)
        prev_doc = orig_doc.latest_id
        new_version = prev_doc.document_version + 1
    except:
        orig_doc = Document(user=User.objects.get(pk=u.id), document_title=doc_title)
        orig_doc.save()
        new_version = 0

    if prev_doc is None or doc_text != prev_doc.document_text:
        DocumentDraft.objects.filter(document=orig_doc, is_latest=True).update(is_latest=False)
        d = DocumentDraft(document=orig_doc, document_text=doc_text, save_date=timezone.now(), is_latest=True, editors_list = editorsString, document_version = new_version)
    else:
        d = prev_doc

    d.save()
    orig_doc.latest_id = d
    orig_doc.save_date = d.save_date
    orig_doc.save()
    return orig_doc.id

def revert(request):
    doc_id = request.POST['doc_id']
    version = request.POST['version']
    document = Document.objects.get(pk = doc_id)
    draft = DocumentDraft.objects.get(document = document, document_version = version)
    draft.is_latest = True
    draft.save()
    document.latest_id = draft
    document.save()
    DocumentDraft.objects.filter(document_version__gt = version, document = document).delete()
    return HttpResponse(version)

def get_doc_version(request):
    doc_id = request.GET['doc_id']
    version = request.GET['version']
    d = DocumentDraft.objects.get(document = doc_id, document_version = version)
    context = {'draft_text' : d.document_text}
    return HttpResponse(json.dumps(context))
    
def request_edit(request):
    doc_text = request.POST['doc_text']
    doc_title = request.POST['doc_title']
    comment = request.POST['comment'].strip()
    editor_names = request.POST['editor_usernames']
    editors_list = editor_names.split(":")
    doc_id = request.POST['doc_id']
    
    new_doc_id = save_doc_in_db(request, doc_text, doc_title, doc_id, "")
    u = get_user(request)
    orig_doc = Document.objects.get(pk=new_doc_id)
    
    if comment != "":
        text = " requested edits to the document <b><a href='/edit/" + orig_doc.link_hash + "'>" + doc_title + "</a></b>:<br>" + comment
    else:
        text = " requested edits to the document <b><a href='/edit/" + orig_doc.link_hash + "'>" + doc_title + "</a></b>"
    
    failed_editors = []
    
    for editor_name in editors_list[:-1]:
        try:
            e = User.objects.get(username__iexact=editor_name)
            EditRequest.objects.filter(writer=u, editor=e, doc=orig_doc).delete()
            er = EditRequest(writer=u, editor=e, doc=orig_doc, request_date=timezone.now())
            er.save()
            full_text = u.username + text
            message = Message(sender = u, recipient = e, message_text = full_text, date=timezone.now())
            message.save()
            tcu = e.twocentsuser
            tcu.has_unread_message = True
            tcu.save()
        except:
            failed_editors.append(editor_name)
            
    return HttpResponse(failed_editors)

def get_editors_string(edit_count, editors):
    editorsList = editors.split(":")
    
    editorsString = ""
    
    if edit_count == "1":
        editorsString = edit_count + " edit from " + editorsList[0]
    elif len(editorsList) == 2:
        editorsString = edit_count + " edits from " + editorsList[0]
    elif len(editorsList) == 3:
        editorsString = edit_count + " edits from " + editorsList[0] + " and " + editorsList[1]
    elif len(editorsList) > 3:
        otherCount = len(editorsList) - 2
        editorsString = edit_count + " edits from " + editorsList[0] + ", " + editorsList[1] + " and " + otherCount + " others"
        
    return editorsString
    
    
def format_doc_text(text):
    text = text.strip()
    if (text.startswith("<p>") == False):
         first_part = text.split("<p>")[0]
         remainder = "<p>".join(text.split("<p>")[1:])
         if remainder != "":
             remainder = "<p>" + remainder
         text = "<p>" + first_part + "</p>" + remainder
    return text
    
def save_document(request):
    doc_text = request.POST['doc_text']
    doc_title = request.POST['doc_title']
    doc_id = request.POST['doc_id']
    edit_count = request.POST['edit_count']
    editors = request.POST.get('editors_dict', "")
    editorsString = get_editors_string(edit_count, editors)
    
    text = format_doc_text(doc_text)
        
    new_doc_id = save_doc_in_db(request, text, doc_title, doc_id, editorsString)
    return HttpResponse(new_doc_id)
    
def save_document_as_edit(request):
    u = get_user(request)
    doc_text = request.POST['doc_text']
    doc_title = request.POST['doc_title']
    doc_id = request.POST['doc_id']
    edit_count = request.POST['edit_count']
    editors = request.POST.get('editors_dict', "")
    editorsString = get_editors_string(edit_count, editors)
    
    text = format_doc_text(doc_text)
    
    orig_doc = Document.objects.get(pk=doc_id)
    prev_doc = orig_doc.latest_id
    new_version = prev_doc.document_version + 1
    author=orig_doc.user
    DocumentDraft.objects.filter(document=orig_doc, is_latest=True).update(is_latest=False)
    d = DocumentDraft(document=orig_doc, document_text=text, save_date=timezone.now(), is_edit=True, is_latest=True, edit_count=edit_count, editors_list = editorsString, document_version = new_version)
    d.save()
        
    orig_doc.latest_id = d
    orig_doc.save_date = d.save_date
    orig_doc.save()
    
    EditRequest.objects.filter(writer=author, editor= u, doc=orig_doc).delete()
    
    full_text = u.username + " submitted " + edit_count + " edits to the document <b><a href='/write/" + orig_doc.link_hash + "'>" + doc_title + "</a></b>"
    message = Message(sender = u, recipient = author, message_text = full_text, date=timezone.now())
    message.save()
    tcu = author.twocentsuser
    tcu.has_unread_message = True
    tcu.save()
    
    
    return HttpResponse(d.id)

def get_web_content(request):
    url = request.POST['url']
    source_type = request.POST['source_type']
    if source_type == "website":
        if url.startswith("http://") == False:
            url = "http://" + url
        r = requests.get(url)
        root = lxml.html.fromstring(r.content)
        description = "HELLO THERE"
        title = ""
        for tit in root.xpath("//meta[@property='og:title']"):
            title = tit.get("content")
        for tit in root.xpath("//meta[@name='title']"):
            title = tit.get("content")
        if title == "":
            for tit in reversed(root.xpath("//h1[@class='title']")):
                title = tit.text_content()
        if title == "":
            for tit in reversed(root.cssselect("title")):
                title = tit.text_content()

        author = "";
        for auth in root.xpath("//meta[@name='author']"):
            author = auth.get("content")
        if author == "":
            for auth in root.xpath("//a[@rel='author']"):
                author = auth.text_content()

        pub_date = ""

        site_name = ""
        for site in root.xpath("//meta[@property='og:site_name']"):
            site_name = site.get("content")

        return HttpResponse(json.dumps({"title" : title, "author" : author, "year" : pub_date, "publisher" : site_name}))

    else:
        isbn = ""
        if isbnlib.is_isbn10(url) or isbnlib.is_isbn13(url):
            isbn = url
        else:
            isbn = isbnlib.isbn_from_words(url)
        metaDict = None
        metaDict = isbnlib.meta(isbn, service='goob', cache=None)
        if metaDict is not None:
            author = metaDict.get("Authors")
            publisher = metaDict.get("Publisher")
            title = metaDict.get("Title")
            year = metaDict.get("Year")
            context = {'title': title, 'author':author, 'publisher':publisher, 'year':year}

write/templates/write/index.html
{% extends "base.html" %}
{% block onReady %}


                function saveDoc() {
                  $.ajax({
                           type: "POST",
                           url: "{% url 'write:save_document' %}",
                           data: {'doc_id': $("#docId").val(), 'doc_title': $(".title").val(), 'doc_text': htmlDecode($("#textbody").text()), 'csrfmiddlewaretoken': '{{csrf_token}}'},
                           dataType: "text",
                           success: function(response) {
                                $("#docId").val(response);
                                alert($("#docId").val());
                            },
                            error: function(rs, e) {
                                   alert(rs.responseText);
                            }
                      });

                }

              $(".saveDocument").on("click", function(){ 
                    saveDoc();
                });


              $(".requestEdit").on("click", function(){
                                   alert($(".editorUsername").val());
                  $.ajax({
                           type: "POST",
                           url: "{% url 'write:request_edit' %}",
                           data: {'doc_title': $(".title").val(), 'doc_text': $("#textbody").text(), 'doc_id': $("#docId").val(), 'editor_username': $(".editorUsername").val(), 'csrfmiddlewaretoken': '{{csrf_token}}'},
                           dataType: "text",
                           success: function(response) {
                                    alert("Requested Edit from " + $(".title").val())
                            },
                            error: function(rs, e) {
                                   alert(rs.responseText);
                            }
                      }); 
                });



html = htmlDecode("{{selected_doc.document_text}}");
$(".editField").append(html);



$(".title").val("{{selected_doc.document_title}}");

$(".cts-1").wrap('<div class="trackedChange" style="display:inline" contenteditable="false"></div>');

//$(".cts-1").wrap('<div class="dropClass" style="display:inline"><li class="ctsWrapper" style="display:inline"></li></div>');

//$(".cts-1").after('<ul><div class="accept change">Accept</div><div class="reject change">Reject</div></ul>');

//$(".dropClass").dropit({action: "mouseenter", triggerEl : ".cts-1"});

    $(".trackedChange").on("mouseenter", function() {
        $(document).find(".trackedChange").removeClass("currentTarget");
        $(this).addClass("currentTarget");
});

function removeIns(){
     $(".currentTarget").remove() 
}

    $(".ins").tooltip({
        show: null, // show immediately 
        content: '<button class="accept change" onclick=$(".currentTarget").after($(".currentTarget").text()).remove()><img src="http://placehold.it/20x20"></button><button class="reject change" onclick=$(".currentTarget").remove()><img src="http://placehold.it/20x20"></button>', //from params
//        track: true,
        position: { my: "center top+10", at: "center" },
        hide: { effect: "" }, //fadeOut
        close: function(event, ui){
            ui.tooltip.hover(
                function () {
                    $(this).stop(true).fadeTo(400, 1); 
                },
                function () {
                    $(this).fadeOut("400", function(){
                        $(this).remove(); 
                    })
                }
            );
        }
    });

    $(".del").tooltip({
        show: null, // show immediately 
        content: '<button class="accept change" onclick=$(".currentTarget").remove()><img src="http://placehold.it/20x20"></button><button class="reject change" onclick=$(".currentTarget").after($(".currentTarget").text()).remove()><img src="http://placehold.it/20x20"></button>', //from params
//        track: true,
        position: { my: "center top+10", at: "center" },
        hide: { effect: "" }, //fadeOut
        close: function(event, ui){
            ui.tooltip.hover(
                function () {
                    $(this).stop(true).fadeTo(400, 1); 
                },
                function () {
                    $(this).fadeOut("400", function(){
                        $(this).remove(); 
                    })
                }
            );
        }
    });


{% endblock %}
{% block headerContent %}

<form action="{% url 'write:publish_document' %}" method="post" id="publishForm">
    {% csrf_token %}
                <input class="title" type="text" name="doc_title" placeholder="My Magnum Opus"/>
                <input id="docId" type="hidden" value="0"/>
</form>
{% endblock %}

{% block middleContent %}
        <div class="paddingDiv">
          <div class="column"><div class="articlePaddingDiv"><div id="textbody" class="editField" contenteditable="true"></div></div></div>
  <input type="submit" form="publishForm" value="Submit">

            <div class="saveDocument">Save</div>
                <input class="editorUsername" type="text" placeholder="Editor"/>
            <div class="requestEdit">Request Edit</div>
            
            <script type="text/javascript">
            
            var u_id = "{{user.id}}";
            var u_name = "{{user.username}}";
     // setup and start event handling for track changes
     tracker.startTracking();
            
}); 
            </script>
</div>
{% endblock %}

write/templates/write/mydrafts.html
{% extends "base.html" %}
{% block onReady %}

              $.ajax({
                       type: "POST",
                       url: "{% url 'browse:get_latest_revs' %}",
                       data: {'csrfmiddlewaretoken': '{{csrf_token}}', 'count': 50},
                       dataType: "text",
                       success: function(response) {
                           $(response).find("object").each(function() {
                               title = $(this).find('[name="document_title"]').text();
                               hash = $(this).find('[name="link_hash"]').text();
                                isPublishedString = "";
                                isPublished = $(this).find('[name="has_been_published"]').text();
                                if (isPublished === "True") {
                                    isPublishedString = " | Published";
                                }
                               editCount = $(this).find('[name="edit_count"]').text();
                               editorsList = $(this).find('[name="editors_list"]').text();
                               $('.articlePaddingDiv').append(
                                    $('<div class="middleSelection">').append(
                                        $('<a>').attr('href','/write/' + hash).append(title + isPublishedString).append(
                                            $('<div class="editString">').append(editorsList)
                                        )
                                    )
                               );    
                           });
                        },
                        error: function(rs, e) {
                               alert(rs.responseText);
                        }
                  }); 

{% endblock %}
{% block middleContent %}

        <div class="paddingDiv">
          <div class="column">
              <div class="articlePaddingDiv">
                  <div class="middleSelection"><a class="clickable newDocButton" href="#"><i class="fa fa-plus"></i> New Document</a></div>
              </div>
            </div>
        </div>

{% endblock %}

write/templates/write/revise.html
{% extends "base.html" %}

{% block onReady %}

function htmlDecode(input){
  var e = document.createElement('div');
  e.innerHTML = input;
  return e.childNodes.length === 0 ? "" : e.childNodes[0].nodeValue;
}

//html = htmlDecode("{{selected_doc.document_text}}");
//$("#rightHere").append(html);

{% endblock %}

{% block headerContent %}

<div class="title" type="text" name="doc_title">{{selected_doc.document_title}}</div>
                <input id="docId" type="hidden" value="0"/>
{% endblock %}

{% block middleContent %}
        <div class="paddingDiv">
          <div class="column"><div class="articlePaddingDiv" id="rightHere" >{{selected_doc.latest_id.document_text | safe }}</div></div>
            
</div>
{% endblock %}